node-option:
  - import=ts-node/register/transpile-only
  - no-warnings
exit: true
recursive: true
extension:
  - ts
ui: bdd
allow-uncaught: false
reporter: dot
watch-files:
  - "src/**/*.ts"
  - "test/**/*.ts"
